{{- if .Values.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "zot.labels" . | nindent 4 }}
type: Opaque
data:
  config.json: {{ mustToJson .Values.config | b64enc }}
{{- end }}
